# Snapshot report for `test/log.js`

The actual snapshot is saved in `log.js.snap`.

Generated by [AVA](https://avajs.dev).

## should fire opts.log() with arguments | uncaughtException

> Snapshot 1

    [
      `×  uncaughtException (an exception was thrown but not caught)  Error: message␊
          const error = new Error('message')␊
                        ^␊
      ␊
      Error: message␊
          at STACK TRACE`,
      'UncaughtException: an exception was thrown but not caught: Error: message',
      [],
      'error',
      Error {
        message: 'message',
      },
    ]

## should fire opts.log() with arguments | unhandledRejection

> Snapshot 1

    [
      `×  unhandledRejection (a promise was rejected but not handled)  Error: message␊
        Promise.reject(new Error('message'))␊
                       ^␊
      ␊
      Error: message␊
          at STACK TRACE`,
      'UnhandledRejection: a promise was rejected but not handled: Error: message',
      [],
      'error',
      Error {
        message: 'message',
      },
    ]

## should fire opts.log() with arguments | rejectionHandled

> Snapshot 1

    [
      `×  rejectionHandled (a promise was rejected and handled too late)  Error: message␊
        const promise = Promise.reject(new Error('message'))␊
                                       ^␊
      ␊
      Error: message␊
          at STACK TRACE`,
      'RejectionHandled: a promise was rejected and handled too late: Error: message',
      [],
      'error',
      Error {
        message: 'message',
      },
    ]

## should fire opts.log() with arguments | multipleResolves

> Snapshot 1

    [
      `i  multipleResolves (a promise was  multiple times) ␊
      Initially resolved with: { success: true }␊
      Then rejected with: Error: message␊
        return new Error('message')␊
               ^␊
      ␊
      Error: message␊
          at STACK TRACE`,
      `MultipleResolves: a promise was resolved/rejected multiple times:␊
      Initially resolved with: { success: true }␊
      Then rejected with: Error: message`,
      [],
      'info',
      Error {
        message: 'message',
      },
      `i  multipleResolves (a promise was resolved multiple times) ␊
      Initially resolved with: { success: true }␊
      Then resolved again with: { success: true }`,
      `MultipleResolves: a promise was resolved multiple times:␊
      Initially resolved with: { success: true }␊
      Then resolved again with: { success: true }`,
      [],
      'info',
      {
        success: true,
      },
      `i  multipleResolves (a promise was  multiple times) ␊
      Initially rejected with: Error: message␊
      Then resolved with: { success: true }`,
      `MultipleResolves: a promise was resolved/rejected multiple times:␊
      Initially rejected with: Error: message␊
      Then resolved with: { success: true }`,
      [],
      'info',
      {
        success: true,
      },
      `i  multipleResolves (a promise was rejected multiple times) ␊
      Initially rejected with: Error: message␊
      Then rejected again with: Error: message␊
        return new Error('message')␊
               ^␊
      ␊
      Error: message␊
          at STACK TRACE`,
      `MultipleResolves: a promise was rejected multiple times:␊
      Initially rejected with: Error: message␊
      Then rejected again with: Error: message`,
      [],
      'info',
      Error {
        message: 'message',
      },
    ]

## should fire opts.log() with arguments | warning

> Snapshot 1

    [
      `‼  warning (WarningType)  message␊
      [500] Detail␊
        emitWarning('message', { type, code, detail })␊
        ^␊
      ␊
      WarningType: message␊
          at STACK TRACE`,
      `Warning: WarningType: message␊
      [500] Detail`,
      [
        'code',
        'detail',
      ],
      'warn',
      WarningType (Error) {
        code: '500',
        detail: 'Detail',
        message: 'message',
      },
      `‼  warning (WarningType1)  message␊
      [500] ␊
        emitWarning('message', { type, code, detail })␊
        ^␊
      ␊
      WarningType1: message␊
          at STACK TRACE`,
      `Warning: WarningType1: message␊
      [500] `,
      [
        'code',
      ],
      'warn',
      WarningType1 (Error) {
        code: '500',
        message: 'message',
      },
      `‼  warning (WarningType2)  message␊
      Detail␊
        emitWarning('message', { type, code, detail })␊
        ^␊
      ␊
      WarningType2: message␊
          at STACK TRACE`,
      `Warning: WarningType2: message␊
      Detail`,
      [
        'detail',
      ],
      'warn',
      WarningType2 (Error) {
        detail: 'Detail',
        message: 'message',
      },
      `‼  warning (WarningType3)  message␊
        emitWarning('message', { type, code, detail })␊
        ^␊
      ␊
      WarningType3: message␊
          at STACK TRACE`,
      'Warning: WarningType3: message',
      [],
      'warn',
      WarningType3 (Error) {
        message: 'message',
      },
    ]
